include:
  - infrastructure.yml
services:
  userservice:
    build: ./sdekapi/userservice/
    ports:
      - "8000:8000"

  consumerservice:
    build: ./sdekapi/consumerservice/
    ports:
      - "8001:8001"
    depends_on:
      - userreadservice

  employeeservice:
    build: ./sdekapi/employeeservice/
    ports:
      - "8002:8002"
    depends_on:
      - consumerreadservice

  packageservice:
    build: ./sdekapi/packageservice/
    ports:
      - "8003:8003"
    depends_on:
      - messenderservice

  messenderservice:
    build: ./sdekapi/messenderservice/
    ports:
      - "8004:8004"
    depends_on:
      - servicesreadservice

  transportservice:
    build: ./sdekapi/transportservice/
    ports:
      - "8005:8005"
    depends_on:
      - warehousereadservice

  warehouseservice:
    build: ./sdekapi/warehouseservice/
    ports:
      - "8006:8006"
    depends_on:
      - employereadeservice

  deliverypersonellservice:
    build: ./sdekapi/deliverypersonellservice/
    ports:
      - "8007:8007"
    depends_on:
      - transportreadservice

  servicesservice:
    build: ./sdekapi/servicesservice/
    ports:
      - "8008:8008"
    depends_on:
      - deliverypersonellreadservice

  userreadservice:
    build: 
      context: ./sdekapi/userreadservice/
    ports:
      - "8010:8010"
    depends_on:
      - userservice

  consumerreadservice:
    build: 
      context: ./sdekapi/consumerreadservice/
    ports:
      - "8011:8011"
    depends_on:
      - consumerservice

  employereadeservice:
    build: 
      context: ./sdekapi/employereadeservice/
    ports:
      - "8012:8012"
    depends_on:
      - employeeservice

  packagereadservice:
    build: 
      context: ./sdekapi/packagereadservice/
    ports:
      - "8013:8013"
    depends_on:
      - packageservice

  transportreadservice:
    build:
      context: ./sdekapi/transportreadservice/
    ports:
      - "8015:8015"
    depends_on:
      - transportservice

  warehousereadservice:
    build: 
      context: ./sdekapi/warehousereadservice/
    ports:
      - "8016:8016"
    depends_on:
      - warehouseservice

  deliverypersonellreadservice:
    build: 
      context: ./sdekapi/deliverypersonellreadservice/
    ports:
      - "8017:8017"
    depends_on:
      - deliverypersonellservice

  servicesreadservice:
    build: 
      context: ./sdekapi/servicesreadservice/
    ports:
      - "8018:8018"
    depends_on:
      - servicesservice

  authservice:
    build: 
      context: ./sdekapi/authservice/
    ports:
      - "8020:8020"
    depends_on:
      - packagereadservice